name: workflow_1
on: push
jobs:
  code_checkout:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4

  build:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
    
      - name: printing the html content
        run: cat index.html

      - name: upload-artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-artifact
          path: index.html

      - name: Trigger REPO_B
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.GIT_CROSS_REPO_TOKEN }}" \
          https://api.github.com/repos/Devtoolllllllllll/REPO_B/dispatches \
          -d '{"event_type":"artifact-ready"}'  
              
 
   

